In [3]:
import numpy as np

# 恒等函数和softmax函数

In [10]:
def softmax(a):
    y = np.exp(a) / np.sum(np.exp(a))
    return y

# 实现softmax函数时的注意事项

In [ ]:
# 溢出
a = np.array([1010, 1000, 900])
np.exp(a) / np.sum(np.exp(a))

C:\Users\40287\AppData\Local\Temp\ipykernel_15100\481425995.py:2: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a))
C:\Users\40287\AppData\Local\Temp\ipykernel_15100\481425995.py:2: RuntimeWarning: invalid value encountered in divide
  np.exp(a) / np.sum(np.exp(a))


array([nan, nan, nan])

In [15]:
c = np.max(a)
np.exp(a - c) / np.sum(np.exp(a - c))

array([9.99954602e-01, 4.53978687e-05, 1.68883521e-48])

In [16]:
# 重新实现softmax
def softmax(a):
    c = np.max(a)
    return np.exp(a - c) / np.sum(np.exp(a - c))

# softmax函数的特征

In [18]:
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print(y)
np.sum(y)

[0.01821127 0.24519181 0.73659691]


np.float64(1.0)