In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
b = a
b *= 2
print(a)
print(a is b)

[2 4 6]
True


In [4]:
a = np.array([1, 2, 3])
b = a
b = b * 2
print(a)
print(a is b)

[1 2 3]
False


In [7]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
d = c[np.array([1, 2]), np.array([1, 2])]
d

array([5, 9])